apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-indexer-repair-deployment
  namespace: starcoin-main
  labels:
    app: starcoin-indexer-repair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-indexer-repair
  template:
    metadata:
      labels:
        app: starcoin-indexer-repair
    spec:
      containers:
        - name: starcoin-indexer-repair
          image: starcoin/starcoin_search:sha-31956df
          ports:
            - containerPort: 8300
          env:
            - name: HOSTS
              value: "main1.seed.starcoin.org"
            - name: NETWORK
              value: "main"
            - name: BG_TASK_JOBS
              value: ""
            - name: BULK_SIZE
              value: "80"
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
            - name: STARCOIN_ES_URL
              value: "123.57.40.36"
            - name: STARCOIN_ES_PROTOCOL
              value: "http"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: SWAP_API_URL
              value: "https://swap-api.starcoin.org"
            - name: SWAP_CONTRACT_ADDR
              value: "0xbd7e8be8fae9f60f2f5136433e36a091"
            - name: DS_URL
              value: "jdbc:postgresql://123.57.40.36:8432/starcoin"
            - name: DB_USER_NAME
              value: "starcoin"
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pw-starcoin
                  key: password
            - name: DB_SCHEMA
              value: "main"
            - name: PROGRAM_ARGS
              value: "auto_repair 1469200"
