apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-api-deployment
  labels:
    app: scan-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scan-api
  template:
    metadata:
      labels:
        app: scan-api
    spec:
      containers:
        - name: scan-api
          image: starcoin/starcoin_scan:sha-c12f628
          ports:
            - name: http
              containerPort: 8500
            - name: multicast
              containerPort: 5701
          env:
            - name: STARCOIN_ES_URL
              value: "search-starcoin-es2-47avtmhexhbg7qtynzebcnnu64.ap-northeast-1.es.amazonaws.com"
            - name: STARCOIN_ES_PROTOCOL
              value: "https"
            - name: STARCOIN_ES_PORT
              value: "443"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: STARCOIN_ES_INDEX_VERSION
              value: ".0727"
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
            - name: MAIN_DS_URL
              value: "jdbc:postgresql://starcoin-pg.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com/starcoin?currentSchema=main"
            - name: DS_URL
              value: "jdbc:postgresql://starcoin-pg.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com/starcoin"
            - name: BARNARD_DS_URL
              value: "jdbc:postgresql://starcoin-pg.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com/starcoin?currentSchema=barnard"
            - name: HALLEY_DS_URL
              value: "jdbc:postgresql://starcoin-pg.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com/starcoin?currentSchema=halley"
            - name: STARCOIN_USER_DS_URL
              value: "jdbc:postgresql://starcoin-pg.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com/starcoin?currentSchema=starcoin_user"
            - name: DB_USER_NAME
              value: "starcoin"
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-starcoin-yu
                  key: password

