apiVersion: v1
kind: Service
metadata:
  labels:
    app: scan-test-api
  name: hazelcast-service
spec:
  selector:
    app: scan-test-api
  ports:
    - name: multicast
      port: 5701
  type: LoadBalancer